# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ci_reporter}
  s.version = "1.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Sieger"]
  s.date = %q{2009-09-03}
  s.email = %q{nick@nicksieger.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.txt"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "LICENSE.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "acceptance/rspec_example_spec.rb",
     "acceptance/test_unit_example_test.rb",
     "acceptance/verification_spec.rb",
     "ci_reporter.gemspec",
     "lib/ci/reporter/core.rb",
     "lib/ci/reporter/rake/rspec.rb",
     "lib/ci/reporter/rake/rspec_loader.rb",
     "lib/ci/reporter/rake/test_unit.rb",
     "lib/ci/reporter/rake/test_unit_loader.rb",
     "lib/ci/reporter/report_manager.rb",
     "lib/ci/reporter/rspec.rb",
     "lib/ci/reporter/test_suite.rb",
     "lib/ci/reporter/test_unit.rb",
     "lib/ci/reporter/version.rb",
     "spec/ci/reporter/output_capture_spec.rb",
     "spec/ci/reporter/rake/rake_tasks_spec.rb",
     "spec/ci/reporter/report_manager_spec.rb",
     "spec/ci/reporter/rspec_spec.rb",
     "spec/ci/reporter/test_suite_spec.rb",
     "spec/ci/reporter/test_unit_spec.rb",
     "spec/spec_helper.rb",
     "stub.rake",
     "tasks/ci_reporter.rake"
  ]
  s.homepage = %q{http://github.com/nicksieger/ci_reporter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Generate reams of XML for use with continuous integration systems.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/ci/reporter/test_unit_spec.rb",
     "spec/ci/reporter/report_manager_spec.rb",
     "spec/ci/reporter/rake/rake_tasks_spec.rb",
     "spec/ci/reporter/rspec_spec.rb",
     "spec/ci/reporter/test_suite_spec.rb",
     "spec/ci/reporter/output_capture_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
